import { useState } from 'react';
import Head from 'next/head';

var TONES = ['Profesional', 'Directo', 'Diplomatico', 'Empatico', 'Firme'];
var LANGUAGES = ['Espanol', 'English', 'Portugues'];
var LANG_LABELS = { 'Espanol': 'Espanol', 'English': 'English', 'Portugues': 'Portugues' };

var BLUE = '#1B4FD8';
var BLUE_LIGHT = '#EEF2FF';
var BG = '#F9F9F7';
var WHITE = '#FFFFFF';
var TEXT = '#111111';
var TEXT2 = '#6B7280';
var TEXT3 = '#9CA3AF';
var BORDER = '#E5E7EB';
var GREEN = '#16A34A';
var GREEN_LIGHT = '#DCFCE7';
var VERSION_COLORS = ['#1B4FD8', '#6366F1', '#8B5CF6'];

export default function Home() {
  var s1 = useState('');
    var message = s1[0]; var setMessage = s1[1];
      var s2 = useState('Profesional');
        var tone = s2[0]; var setTone = s2[1];
          var s3 = useState('English');
            var language = s3[0]; var setLanguage = s3[1];
              var s4 = useState(false);
                var loading = s4[0]; var setLoading = s4[1];
                  var s5 = useState(null);
                    var versions = s5[0]; var setVersions = s5[1];
                      var s6 = useState('');
                        var error = s6[0]; var setError = s6[1];
                          var s7 = useState(null);
                            var copied = s7[0]; var setCopied = s7[1];

                              async function handleGenerate() {
                                  if (!message.trim()) return;
                                      setLoading(true); setError(''); setVersions(null);
                                          try {
                                                var res = await fetch('/api/write', {
                                                        method: 'POST',
                                                                headers: { 'Content-Type': 'application/json' },
                                                                        body: JSON.stringify({ message: message, tone: tone, language: language })
                                                                              });
                                                                                    var data = await res.json();
                                                                                          if (data.error) { setError('Something went wrong. Please try again.'); }
                                                                                                else { setVersions(data.versions); }
                                                                                                    } catch (e) {
                                                                                                          setError('Connection error. Please try again.');
                                                                                                              } finally { setLoading(false); }
                                                                                                                }
                                                                                                                
                                                                                                                  async function handleCopy(text, idx) {
                                                                                                                      try {
                                                                                                                            await navigator.clipboard.writeText(text);
                                                                                                                                  setCopied(idx);
                                                                                                                                        setTimeout(function() { setCopied(null); }, 2000);
                                                                                                                                            } catch (e) {}
                                                                                                                                              }
                                                                                                                                              
                                                                                                                                                var isDisabled = !message.trim() || loading;
                                                                                                                                                
                                                                                                                                                  return (
                                                                                                                                                      <div style={{ minHeight: '100vh', background: BG, fontFamily: "'Inter', system-ui, sans-serif", padding: '0 1rem' }}>
                                                                                                                                                            <Head>
                                                                                                                                                                    <title>EzWrite - AI Message Writer</title>
                                                                                                                                                                            <meta name="description" content="Turn your rough message into 3 polished versions instantly." />
                                                                                                                                                                                    <link rel="preconnect" href="https://fonts.googleapis.com" />
                                                                                                                                                                                            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
                                                                                                                                                                                                    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
                                                                                                                                                                                                          </Head>
                                                                                                                                                                                                                <div style={{ maxWidth: '640px', margin: '0 auto', paddingTop: '3rem', paddingBottom: '4rem' }}>
                                                                                                                                                                                                                        <div style={{ marginBottom: '2.5rem' }}>
                                                                                                                                                                                                                                  <div style={{ fontFamily: "'DM Serif Display', Georgia, serif", fontSize: '2rem', color: TEXT, letterSpacing: '-0.02em', display: 'flex', alignItems: 'center', gap: '8px' }}>
                                                                                                                                                                                                                                              <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: BLUE, display: 'inline-block' }}></span>
                                                                                                                                                                                                                                                          EzWrite
                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                              <p style={{ fontSize: '14px', color: TEXT2, marginTop: '6px' }}>Paste your rough message. Get 3 polished versions, instantly.</p>
                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                              <div style={{ marginBottom: '1.5rem' }}>
                                                                                                                                                                                                                                                                                                        <span style={{ fontSize: '11px', fontWeight: 600, letterSpacing: '0.07em', textTransform: 'uppercase', color: TEXT3, marginBottom: '8px', display: 'block' }}>Your message</span>
                                                                                                                                                                                                                                                                                                                  <textarea style={{ width: '100%', minHeight: '120px', padding: '12px 14px', border: '1px solid ' + BORDER, borderRadius: '8px', fontSize: '14px', color: TEXT, background: WHITE, resize: 'vertical', fontFamily: "'Inter', system-ui, sans-serif", lineHeight: 1.6, boxSizing: 'border-box' }} placeholder="Write what you want to say, as rough as you like..." value={message} onChange={function(e) { setMessage(e.target.value); }} />
                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                  <div style={{ marginBottom: '1.5rem' }}>
                                                                                                                                                                                                                                                                                                                                            <span style={{ fontSize: '11px', fontWeight: 600, letterSpacing: '0.07em', textTransform: 'uppercase', color: TEXT3, marginBottom: '8px', display: 'block' }}>Tone</span>
                                                                                                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                                  {TONES.map(function(t) {
                                                                                                                                                                                                                                                                                                                                                                                var active = tone === t;
                                                                                                                                                                                                                                                                                                                                                                                              return (<button key={t} onClick={function() { setTone(t); }} style={{ padding: '7px 14px', borderRadius: '6px', border: active ? '1.5px solid ' + BLUE : '1px solid ' + BORDER, background: active ? BLUE_LIGHT : WHITE, color: active ? BLUE : TEXT2, fontSize: '13px', fontWeight: active ? 600 : 400, cursor: 'pointer', fontFamily: "'Inter', system-ui, sans-serif" }}>{t}</button>);
                                                                                                                                                                                                                                                                                                                                                                                                          })}
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ marginBottom: '1.5rem' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ fontSize: '11px', fontWeight: 600, letterSpacing: '0.07em', textTransform: 'uppercase', color: TEXT3, marginBottom: '8px', display: 'block' }}>Output language</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {LANGUAGES.map(function(l) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var active = language === l;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (<button key={l} onClick={function() { setLanguage(l); }} style={{ padding: '7px 14px', borderRadius: '6px', border: active ? '1.5px solid ' + BLUE : '1px solid ' + BORDER, background: active ? BLUE_LIGHT : WHITE, color: active ? BLUE : TEXT2, fontSize: '13px', fontWeight: active ? 600 : 400, cursor: 'pointer', fontFamily: "'Inter', system-ui, sans-serif" }}>{LANG_LABELS[l] || l}</button>);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button style={{ width: '100%', padding: '13px', background: isDisabled ? BORDER : BLUE, color: isDisabled ? TEXT3 : WHITE, border: 'none', borderRadius: '8px', fontSize: '15px', fontWeight: 600, cursor: isDisabled ? 'not-allowed' : 'pointer', fontFamily: "'Inter', system-ui, sans-serif", marginTop: '0.5rem' }} onClick={handleGenerate} disabled={isDisabled}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {loading ? 'Writing...' : 'Generate 3 versions'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {error && (<div style={{ background: '#FEF2F2', border: '1px solid #FCA5A5', color: '#DC2626', borderRadius: '8px', padding: '12px 14px', fontSize: '13px', marginTop: '1rem' }}>{error}</div>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {versions && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ height: '1px', background: BORDER, margin: '2rem 0' }}></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {versions.map(function(v, idx) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var color = VERSION_COLORS[idx] || BLUE;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      var isCopied = copied === idx;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={idx} style={{ background: WHITE, border: '1px solid ' + BORDER, borderLeft: '3px solid ' + color, borderRadius: '10px', padding: '16px', marginBottom: '12px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={{ fontSize: '12px', fontWeight: 700, padding: '3px 8px', borderRadius: '4px', background: color + '18', color: color }}>{v.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={function() { handleCopy(v.text, idx); }} style={{ fontSize: '12px', fontWeight: 500, padding: '5px 12px', borderRadius: '6px', border: isCopied ? '1px solid ' + GREEN : '1px solid ' + BORDER, background: isCopied ? GREEN_LIGHT : WHITE, cursor: 'pointer', color: isCopied ? GREEN : TEXT2, fontFamily: "'Inter', system-ui, sans-serif" }}>{isCopied ? 'Copied!' : 'Copy'}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{ fontSize: '14px', lineHeight: 1.7, color: TEXT, margin: 0, whiteSpace: 'pre-wrap' }}>{v.text}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginTop: '3rem', paddingTop: '1.5rem', borderTop: '1px solid ' + BORDER, textAlign: 'center', fontSize: '12px', color: TEXT3 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Made with <span style={{ color: BLUE, fontFamily: "'DM Serif Display', Georgia, serif" }}>EzWrite</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
